config/routes.rb
Rails.application.routes.draw do
  get 'about' => 'pages#about', as: :about
  get 'contact' => 'pages#contact', as: :contact
  root to: "projects#index"
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def about
  end
  
  def contact
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_navbar.html.erb
<% unless action_name == "homepage" %>
  <nav>
    <div class="site-width">
      <a href="" target="_blank">Michelle Gerber</a>
      <span class="menu icon" title="Menu (Esc)" tabindex="0" data-icon="m"><span>Menu</span></span>
    <div>

	<div id="navigation">
     <ul>
	   <li class='list-group-item'>
 		<%= link_to "Projects", projects_path, class:"nav-link #{yield(:projects_active)}" %>
   	   </li>
	   <li class="list-group-item">
	 	<%= link_to "About", about_path, class:"nav-link #{yield(:about_active)}" %>
	   </li>
	   <li class="list-group-item">
		<%= link_to "Contact", contact_path, class:"nav-link #{yield(:contact_active)}" %>
	   </li>
	  <% end %>
	 </ul>
	</div>
	</div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | MG </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <%= render 'layouts/navbar' %>
	<div class="container <%= controller_name %> <%= action_name %>">
     <%= yield %>
    </div>
  </body>
    <%= javascript_include_tag 'navbar.js' %>
</html>

app/views/pages/about.html.erb
<% provide(:about_active, 'active') %>
<div class="container">

  <div id="profile-header">
    <div>
      <div id="profile-picture-container">
        <div>
          <%= image_tag('meside.jpg', id: "profile-picture") %>
        </div>
      </div>
      <div id="profile-links">
	         <%= render 'profile_links' %>
	       </div>
	     </div>
	   </div>
  
	    <div class="section" id="about-me">
	       <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2"
	               id="about-me-description">
	         <%= render 'about_me_description' %>
	       </div>
	     </div>

	     <%= render partial: 'layouts/shared/section_header',
	                locals: { header_class: "col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2",
	                          header_title: "Photography" }
	     %>

	     <div class="section" id="photography">
	       <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2"
	               id="album-list">
	         <%= render 'album_list' %>
	       </div>
	     </div>

	     <%= render partial: 'layouts/shared/section_header',
	                locals: { header_class: "col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2",
	                          header_title: "Authors and Philosophical Leanings" }
	     %>

	     <div class="section" id="projects">
	       <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2"
	               id="authors-list">
	         <%= render 'authors_list' %>
	       </div>
	     </div>

	   </div>
       

app/views/pages/contact.html.erb
<% provide(:contact_active, 'active') %>
<h1>Contact</h1>

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :link %>
    <%= f.text_field :link %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<% provide(:page_title, "Editing") %>
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<% provide(:page_title, "Stuffs") %>
<% provide(:projects_active, 'active') %>
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Link</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.link %></td>
        <td><%= project.slug %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<% provide(:page_title, @project.title) %>
<% provide(:projects_active, 'active') s%>
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<% provide(:page_title, @project.title) %>
<% provide(:projects_active, 'active') %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Link:</strong>
  <%= @project.link %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @project.slug %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>